### ISSUE TITLE
linked list is not woring

### ISSUE THREAD

**Issue by suvasish114** [The-IT-Crew/DBMS#10]
the **node.cpp** file is not working.

![Screenshot from 2021-04-17 10-05-25](https://user-images.githubusercontent.com/64000509/115102394-27ea1700-9f68-11eb-8298-dfd28c22f1ec.png)

**Comment by manasmdg3** [comment]
system restart kore dekhe6s?

**Comment by suvasish114** [comment]
> @suvasish114 system restart kore dekhe6s?

haa ho66e na, sayan handle kor6e linked list ta

**Comment by sayak-ghosh** [comment]
o bhsdiwale chacha @manasmdg3 , dorja khol calling bell baj6e na...

**Comment by suvasish114** [comment]
Lol 😂

**Comment by manasmdg3** [comment]
O bete mouj kar di..! 😂

**Comment by manasmdg3** [comment]
Solved by @sayandey-dev 🔥
